### ISSUE TITLE
FR : Items

### ISSUE THREAD

**Issue by benda95280** [PresentKim/runtimeid-polyfill#1]
Dear PresentKim,

Is there any way to do the same thing with items ?

Thanks.

**Comment by PresentKim** [comment]
All vanilla item ids are registered in pmmp (as I know)
Therefore, already all items can be using.

| How do I check if item ID is registered? |
|------------------------------------------|
| Just execute `/give <playerName> <itemId>` command. <br> If you can give item with item id (And can see it in clients), <br> That means that item id is registered. |

If you know an item ID that doesn't registered, please let me know. then I'll check.

If you talking about the feature implementation of the item, 
`My answer`: `This virion does not implement the block or item, it just registers the missing id.`
