### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ItsRealNise** [PresentKim/runtimeid-polyfill#2]
Update To 1.17?

**Comment by PresentKim** [comment]
This project doesn't have its own resource data.
It always works based on PMMP's resource files.
The function of this virion is to just register the runtime id of the unregistered block(that already exists in the resource file of PMMP) to the map 

If you need new Minecraft block data, please request it to [PMMP/BedrockData](https://github.com/pmmp/BedrockData).

But I know it has already been updated to version 1.17.10... (https://github.com/pmmp/BedrockData/commit/21ec07f14e258d10475a714d77cbdcb7284745ec)
