### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YaNIND** [PresentKim/runtimeid-polyfill#3]
how to register the block? hmms

**Comment by PresentKim** [comment]
- If you are asking how to register block to a BlockFactory?
	- Use `BlockFactory::register()`
- If you are asking how to add block runtime id to RuntimeBlockMapping?
	- Use `RuntimeBlockMapping::registerMapping()`

**Comment by YaNIND** [comment]
> * If you are asking how to register block to a BlockFactory?
>   
>   * Use `BlockFactory::register()`
> * If you are asking how to add block runtime id to RuntimeBlockMapping?
>   
>   * Use `RuntimeBlockMapping::registerMapping()`

RuntimeBockMapping::registerMapping(idblock, what is legacy, metaofblock);

Like This?

**Comment by YaNIND** [comment]
> * If you are asking how to register block to a BlockFactory?
>   
>   * Use `BlockFactory::register()`
> * If you are asking how to add block runtime id to RuntimeBlockMapping?
>   
>   * Use `RuntimeBlockMapping::registerMapping()`

RuntimeBockMapping::registerMapping(idblock, what is legacy, metaofblock);

Like This?

**Comment by YaNIND** [comment]
> > * If you are asking how to register block to a BlockFactory?
> >   
> >   * Use `BlockFactory::register()`
> > * If you are asking how to add block runtime id to RuntimeBlockMapping?
> >   
> >   * Use `RuntimeBlockMapping::registerMapping()`
> 
> RuntimeBockMapping::registerMapping(idblock, what is legacy, metaofblock);
> 
> Like This?

or minecraft:block, idofblock, metaofblock

**Comment by PresentKim** [comment]
```php
private static function registerMapping(int $staticRuntimeId, int $legacyId, int $legacyMeta) : void
```

But it has `private` visibility
If you want call that method, U should use Reflection, which is accessible by ignoring visibility.

If you want to know how to register the `staticRuntimeId`, see the source of this virion.
